myproj/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, CommentCreateView, CommentDeleteView

app_name = "blog"

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_list"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("<int:pk>/update/", BlogUpdateView.as_view(), name="blog_update"),
    path("<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),

    path('<int:blog_pk>/comments/create/',
         CommentCreateView.as_view(), name='comment_create'),
    path('<int:blog_pk>/comments/<int:pk>/delete/',
         CommentDeleteView.as_view(), name='comment_delete'),
]

myproj/catube/urls.py
from django.urls import path
from .views import VideoListView, VideoDetailView, VideoCreateView, VideoUpdateView, VideoDeleteView, CommentCreateView, CommentDeleteView

app_name = "catube"

urlpatterns = [
    path("", VideoListView.as_view(), name="video_list"),
    path("create/", VideoCreateView.as_view(), name="video_create"),
    path("<int:pk>/", VideoDetailView.as_view(), name="video_detail"),
    path("<int:pk>/update/", VideoUpdateView.as_view(), name="video_update"),
    path("<int:pk>/delete/", VideoDeleteView.as_view(), name="video_delete"),

    path('<int:video_pk>/comments/create/',
         CommentCreateView.as_view(), name='comment_create'),
    path('<int:video_pk>/comments/<int:pk>/delete/',
         CommentDeleteView.as_view(), name='comment_delete'),
]

myproj/myproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('rest/', include('rest.urls')),
    path('catube/', include('catube.urls')),
    #path('blog/', include('blog.urls')),

    path("", RedirectView.as_view(pattern_name="catube:video_list"), name="root"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproj/blog/models.py
from django.db import models
from django.forms import CharField, Textarea
from django.conf import settings
from django.urls import reverse


# Create your models here.
class Blog(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    discription = models.TextField()
    start_dt = models.DateTimeField()
    end_dt = models.DateTimeField()
    photo = models.ImageField()
    file = models.FileField()
    view_count = models.PositiveIntegerField(default=0)
    delete_flag = models.CharField(max_length=1, default="N")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('catube:video_detail', args=[self.pk])


class Comment(models.Model):
    video = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

myproj/blog/forms.py
import os
from django import forms
from .models import Blog, Comment


class BlogForm(forms.ModelForm):
    def clean_file(self):
        file = self.cleaned_data.get('file', None)
        if file:
            extension = os.path.splitext(file.name)[-1].lower()
            if extension not in ('.mp4', '.avi'):
                raise forms.ValidationError('비디오 파일을 업로드해주세요.')
        return file

    class Meta:
        model = Blog
        fields = ['title',
                  'description',
                  'start_dt', 'end_dt'
                  'file',
                  'photo']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content',
        ]
        widgets = {
            'content': forms.Textarea(attrs={'rows': 3}),
        }

myproj/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import F
from django.shortcuts import render, get_object_or_404, resolve_url
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, UpdateView, DetailView, CreateView
from .models import Blog, Comment
from .forms import BlogForm, CommentForm


class BlogListView(ListView):
    model = Blog
    paginate_by = 4

    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get('q', '').strip()
        if q:
            qs = qs.filter(title__icontains=q)
        return qs


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    template_name = 'form.html'

    def form_valid(self, form):
        Blog = form.save(commit=False)
        Blog.author = self.request.user
        return super().form_valid(form)


class BlogDetailView(DetailView):
    model = Blog

    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        Blog.objects.filter(pk=pk).update(view_count=F('view_count') + 1)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['comment_form'] = CommentForm()
        return context_data


class BlogUpdateView(UserPassesTestMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    template_name = 'form.html'

    def test_func(self):
        return self.request.user == self.get_object().author


class BlogDeleteView(UserPassesTestMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('catube:Blog_list')

    def test_func(self):
        return self.request.user == self.get_object().author


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'form.html'

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.Blog = get_object_or_404(Blog, pk=self.kwargs['Blog_pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return resolve_url('catube:Blog_detail', self.kwargs['Blog_pk'])


class CommentDeleteView(UserPassesTestMixin, DeleteView):
    model = Comment

    def test_func(self):
        return self.request.user == self.get_object().author

    def get_success_url(self):
        return resolve_url('catube:Blog_detail', self.kwargs['Blog_pk'])

myproj/blog/templates/blog/blog_confirm_delete.html
정말 삭제하겠습니까?

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Go!" />
</form>

myproj/blog/templates/blog/blog_detail.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block content %}
<video controls class="w-100">
    <source src="{{ blog.file.url }}" />
</video>
<h4>{{ blog.title }}</h4>

작성자 : {{ blog.author.email|default:blog.author.username }}
{{ blog.description|linebreaks }}

조회수 : {{ blog.view_count }}

{% if user == blog.author %}
<a href="{% url 'catube:blog_update' blog.pk %}" class="btn btn-danger">수정</a>
<a href="{% url 'catube:blog_delete' blog.pk %}" class="btn btn-outline-danger">삭제</a>
{% endif %}

댓글 ({{ blog.comment_set.all.count }})

<form action="{% url 'catube:comment_create' blog.pk %}" method="post">
    {% csrf_token %}
    {% bootstrap_form comment_form layout="inline" %}
    <input type="submit" value="저장" class="btn btn-danger" />
</form>

<div class="comment-list">
    {% for comment in blog.comment_set.all %}
    <div class="comment">
        작성자: {{ comment.author }}, {{ comment.created_at|timesince }} 전,
        {{ comment.content|linebreaks }}
        {% if user == comment.author %}
        <a href="{% url 'catube:comment_delete' blog.pk comment.pk %}" class="btn btn-outline-danger btn-sm">삭제</a>
        {% endif %}
    </div>

    {% endfor %}
</div>
{% endblock %}

myproj/blog/templates/blog/blog_list.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="row">
    {% for blog in blog_list %}
    <div class="col-3 mb-3">
        <div class="card">
            <img src="{{ blog.photo.url }}" class="w-100" />
            <div class="card-body">
                <a href="{% url 'catube:blog_detail' blog.pk %}" class="text-dark">
                    <strong>{{ blog.title }}</strong>
                    <p class="small">
                        {{ blog.description|truncatechars:30 }}
                    </p>
                    <p class="text-gray small">
                        {{ blog.created_at|timesince }} 전,
                        조회수 : {{ blog.view_count }}
                    </p>
                </a>
            </div>

        </div>

    </div>
    {% endfor %}
</div>


{% bootstrap_pagination page_obj %}

<hr />
<a href="{% url 'catube:blog_create' %}">업로드</a>
{% endblock %}

myproj/blog/templates/blog/comment_confirm_delete.html
정말 삭제하시겠습니까?

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Go!" />
</form>